### ISSUE TITLE
Does deliver support rollback?

### ISSUE THREAD

**Issue by arvenil** [gerhard/deliver#63]
One thing I expect from deployment tool is ability to easily rollback to previous version in case of some failure (e.g. app deployed to production introduces bug and we want quickly revert to older, working version).

Does `deliver` supports that?

**Comment by gerhard** [comment]
A rollback is a push with a specific git tag/version. Say you've delivered git tag v1.0.2 and you discover a bug. To roll back, you deliver git tag v1.0.1. It's the simplest solution to a [complex problem](http://docs.pivotal.io/pivotalcf/devguide/deploy-apps/blue-green.html). The deliver successor will definitely support this, but it's still a few months out. Watch this space :wink:
