### ISSUE TITLE
Staging / Testing

### ISSUE THREAD

**Issue by deatharse** [gerhard/deliver#65]
Just started testing, created config file and a strategy file for composer ... all is fine.

The question I have is how do we handle multiple environments (testing / staging / production)? I can't see anyway to do this other than to completely change the config file each time.

**Comment by gerhard** [comment]
I would go with shim functions, e.g.:

``` sh
deliver_test() {
  HOSTS="test-1,test-2" "$@"
}

deliver_staging() {
  HOSTS="staging-1,staging-2" "$@"
}

deliver_production() {
  HOSTS="prod-1,prod-2" "$@"
}
```

Keep `.deliver/config` common, and have these functions available in your shell env.
